export const abc = [
  { letter: 'A', state: 0 },
  { letter: 'B', state: 0 },
  { letter: 'C', state: 0 },
  { letter: 'D', state: 0 },
  { letter: 'E', state: 0 },
  { letter: 'F', state: 0 },
  { letter: 'G', state: 0 },
  { letter: 'H', state: 0 },
  { letter: 'I', state: 0 },
  { letter: 'J', state: 0 },
  { letter: 'K', state: 0 },
  { letter: 'L', state: 0 },
  { letter: 'M', state: 0 },
  { letter: 'N', state: 0 },
  { letter: 'O', state: 0 },
  { letter: 'P', state: 0 },
  { letter: 'Q', state: 0 },
  { letter: 'R', state: 0 },
  { letter: 'S', state: 0 },
  { letter: 'T', state: 0 },
  { letter: 'U', state: 0 },
  { letter: 'V', state: 0 },
  { letter: 'W', state: 0 },
  { letter: 'X', state: 0 },
  { letter: 'Y', state: 0 },
  { letter: 'Z', state: 0 },
];
