export const rosco = [
  { answer: 'ACIDO', ask: 'Que tiene sabor parecido al vinagre.' },
  { answer: 'BOMBIN', ask: 'Sombrero con forma de hongo o seta.' },
  { answer: 'CANCION', ask: 'Composicion que se canta.' },
  { answer: 'DURMIENTE', ask: 'Que duerme.' },
  { answer: 'ESCRITOR', ask: 'Persona que escribe.' },
  { answer: 'FERROCARRIL', ask: 'Camino con dos filas de barras de hierro por la que circula un tren.' },
  { answer: 'GOLFO', ask: 'Porcion de mar que entra en la tierra.' },
  { answer: 'HOSPITAL', ask: 'Establecimiento en el que se curan enfermos.' },
  { answer: 'IDENTICO', ask: 'Dicese de lo que es igual a otra cosa con la que se compara.' },
  { answer: 'JAGUAR', ask: 'Tigre americano.' },
  { answer: 'BIKINI', ask: 'Contiene la K, conjunto de dos prendas femeninas para el bano.' },
  { answer: 'LAUD', ask: 'Instrumento musical de cuerda.' },
  { answer: 'MOSTRADOR', ask: 'Mesa que hay en las tiendas para mostrar sus productos.' },
  { answer: 'NAVEGAR', ask: 'Viajar por el agua con una embarcacion o nave.' },
  { answer: 'OGRO', ask: 'Gigante de mal caracter como Shrek.' },
  { answer: 'PEGATINA', ask: 'Adhesivo pequeno que lleva impreso un dibujo.' },
  { answer: 'ARQUERO', ask: 'Contiene Q, soldado que peleaba con arco y flecha.' },
  { answer: 'ROSTRO', ask: 'Cara de las personas.' },
  { answer: 'SALIDA', ask: 'Parte por la que se sale de un lugar.' },
  { answer: 'TIJERA', ask: 'Objeto que sirve para cortar.' },
  { answer: 'UNIR', ask: 'Juntar dos o mas cosas.' },
  { answer: 'VIOLETA', ask: 'Color morado claro.' },
  { answer: 'WISKY', ask: 'Bebida que piden los vaqueros en las peliculas.' },
  { answer: 'EXCLUSIVO', ask: 'Contiene la X, unico, solo.' },
  { answer: 'MAYORAL', ask: 'Contiene la Y, pastor principal entre los que cuidan los rebanos.' },
  { answer: 'ZAPATEADO', ask: 'Baile espanol que se ejecuta zapateando.' },
];
